/**
 * Organizational AI Maturity Assessment Questions
 *
 * Comprehensive enterprise assessment across 23 dimensions in 4 categories:
 *
 * TECHNICAL (5 dimensions):
 *   1. Tech Infrastructure - Cloud, data architecture, API integration
 *   2. Data Quality & Governance - Data governance, quality metrics
 *   3. Security & Compliance - Security frameworks, AI ethics
 *   4. Integration & Interoperability - Enterprise integration, API maturity
 *   5. Scalability & Performance - Auto-scaling, performance monitoring
 *
 * HUMAN (5 dimensions):
 *   6. Leadership & Vision - CEO commitment, AI strategy
 *   7. Culture & Change Readiness - Innovation culture, change history
 *   8. Skills & Talent - AI/ML skills gap, training programs
 *   9. Collaboration & Communication - Cross-functional effectiveness
 *   10. Employee Experience - Engagement, digital workplace maturity
 *
 * BUSINESS (7 dimensions):
 *   11. Strategy & Alignment - AI alignment with business strategy
 *   12. Process Optimization - Process automation, documentation
 *   13. Customer Centricity - Customer data, personalization
 *   14. Innovation Capability - Innovation process, R&D budget
 *   15. Financial Performance - Revenue growth, AI investment
 *   16. Partner Ecosystem - Strategic partnerships
 *   17. Risk Management - Risk framework, mitigation strategies
 *
 * AI ADOPTION (6 dimensions):
 *   18. AI Use Cases - Production use cases, business impact
 *   19. ML Operations - MLOps platform, model governance
 *   20. AI Governance - Ethics board, bias monitoring
 *   21. Data Science Maturity - DS team, advanced analytics
 *   22. Automation Level - RPA adoption, intelligent automation
 *   23. AI Infrastructure - GPU infrastructure, AI platform
 *
 * Total: ~70 questions (3 per dimension)
 * Estimated completion time: 35-45 minutes
 */

export interface OrgMaturityQuestion {
  id: string
  code: string
  category: 'technical' | 'human' | 'business' | 'ai_adoption'
  dimension: string
  dimensionName: string
  question: string
  description?: string
  helpText?: string
  answerType: 'scale' | 'multiChoice' | 'boolean' | 'percentage'
  options?: Array<{ value: number; label: string; description?: string }>
  weight: number
  order: number
  isRequired: boolean
  forRoles?: string[] // If specified, only show to these roles (e.g., 'cto', 'cfo', 'chro')
}

// ============================================================
// CATEGORY 1: TECHNICAL (5 Dimensions)
// ============================================================

const technicalQuestions: OrgMaturityQuestion[] = [
  // Tech Infrastructure (3 questions)
  {
    id: 'org-tech-infra-001',
    code: 'TECH_INFRA_001',
    category: 'technical',
    dimension: 'tech_infrastructure',
    dimensionName: 'Technology Infrastructure',
    question: 'What is your organization\'s current cloud adoption level?',
    answerType: 'multiChoice',
    options: [
      { value: 0, label: 'No cloud', description: 'Fully on-premises infrastructure' },
      { value: 25, label: 'Cloud exploring', description: 'Evaluating cloud options, minimal adoption' },
      { value: 50, label: 'Hybrid cloud', description: 'Mix of on-premises and cloud workloads' },
      { value: 75, label: 'Cloud-first', description: 'Most new workloads go to cloud' },
      { value: 100, label: 'Cloud-native', description: 'Fully cloud-native architecture' },
    ],
    weight: 1.2,
    order: 1,
    isRequired: true,
  },
  {
    id: 'org-tech-infra-002',
    code: 'TECH_INFRA_002',
    category: 'technical',
    dimension: 'tech_infrastructure',
    dimensionName: 'Technology Infrastructure',
    question: 'How would you rate your data architecture maturity for AI/ML workloads?',
    answerType: 'scale',
    description: 'Consider data lakes, warehouses, streaming, and ML feature stores.',
    helpText: 'Rate from 0 (no ML-ready architecture) to 100 (enterprise ML platform)',
    weight: 1.1,
    order: 2,
    isRequired: true,
  },
  {
    id: 'org-tech-infra-003',
    code: 'TECH_INFRA_003',
    category: 'technical',
    dimension: 'tech_infrastructure',
    dimensionName: 'Technology Infrastructure',
    question: 'What percentage of your critical business systems have modern APIs?',
    answerType: 'percentage',
    description: 'RESTful or GraphQL APIs that enable integration with AI services.',
    weight: 1.0,
    order: 3,
    isRequired: true,
  },

  // Data Quality & Governance (3 questions)
  {
    id: 'org-data-gov-001',
    code: 'DATA_GOV_001',
    category: 'technical',
    dimension: 'data_quality',
    dimensionName: 'Data Quality & Governance',
    question: 'Does your organization have a formal data governance framework?',
    answerType: 'multiChoice',
    options: [
      { value: 0, label: 'No framework', description: 'No formal data governance' },
      { value: 25, label: 'Basic policies', description: 'Some data policies exist but not enforced' },
      { value: 50, label: 'Defined framework', description: 'Formal framework with data stewards' },
      { value: 75, label: 'Mature governance', description: 'Active governance with metrics and enforcement' },
      { value: 100, label: 'AI-ready governance', description: 'Data governance optimized for ML/AI needs' },
    ],
    weight: 1.2,
    order: 1,
    isRequired: true,
  },
  {
    id: 'org-data-gov-002',
    code: 'DATA_GOV_002',
    category: 'technical',
    dimension: 'data_quality',
    dimensionName: 'Data Quality & Governance',
    question: 'How would you rate the overall quality of your organization\'s data?',
    answerType: 'scale',
    description: 'Consider accuracy, completeness, consistency, and timeliness.',
    helpText: 'Rate from 0 (poor quality) to 100 (excellent quality)',
    weight: 1.1,
    order: 2,
    isRequired: true,
  },
  {
    id: 'org-data-gov-003',
    code: 'DATA_GOV_003',
    category: 'technical',
    dimension: 'data_quality',
    dimensionName: 'Data Quality & Governance',
    question: 'Do you have a centralized data catalog or metadata management system?',
    answerType: 'multiChoice',
    options: [
      { value: 0, label: 'No catalog', description: 'No centralized data documentation' },
      { value: 33, label: 'Basic inventory', description: 'Spreadsheet-based tracking' },
      { value: 66, label: 'Data catalog', description: 'Formal catalog with search and lineage' },
      { value: 100, label: 'AI-enhanced catalog', description: 'ML-powered discovery and recommendations' },
    ],
    weight: 0.9,
    order: 3,
    isRequired: true,
  },

  // Security & Compliance (3 questions)
  {
    id: 'org-security-001',
    code: 'SECURITY_001',
    category: 'technical',
    dimension: 'security_compliance',
    dimensionName: 'Security & Compliance',
    question: 'Which security frameworks and certifications does your organization maintain?',
    answerType: 'multiChoice',
    options: [
      { value: 0, label: 'None', description: 'No formal security certifications' },
      { value: 25, label: 'Basic', description: 'Basic security policies only' },
      { value: 50, label: 'Industry standard', description: 'SOC 2 or ISO 27001' },
      { value: 75, label: 'Multiple frameworks', description: 'SOC 2, ISO 27001, and industry-specific' },
      { value: 100, label: 'Comprehensive', description: 'All major frameworks plus AI-specific ethics guidelines' },
    ],
    weight: 1.1,
    order: 1,
    isRequired: true,
  },
  {
    id: 'org-security-002',
    code: 'SECURITY_002',
    category: 'technical',
    dimension: 'security_compliance',
    dimensionName: 'Security & Compliance',
    question: 'Do you have specific policies for AI/ML model security and data privacy?',
    answerType: 'multiChoice',
    options: [
      { value: 0, label: 'No policies', description: 'No AI-specific security policies' },
      { value: 33, label: 'Basic guidelines', description: 'Informal guidelines for AI projects' },
      { value: 66, label: 'Formal policies', description: 'Documented AI security and privacy policies' },
      { value: 100, label: 'Comprehensive', description: 'Full AI security framework with monitoring' },
    ],
    weight: 1.0,
    order: 2,
    isRequired: true,
  },
  {
    id: 'org-security-003',
    code: 'SECURITY_003',
    category: 'technical',
    dimension: 'security_compliance',
    dimensionName: 'Security & Compliance',
    question: 'How prepared is your organization for AI-related regulatory requirements (EU AI Act, etc.)?',
    answerType: 'scale',
    helpText: 'Rate from 0 (not prepared) to 100 (fully prepared)',
    weight: 0.9,
    order: 3,
    isRequired: true,
  },

  // Integration & Interoperability (3 questions)
  {
    id: 'org-integration-001',
    code: 'INTEGRATION_001',
    category: 'technical',
    dimension: 'integration',
    dimensionName: 'Integration & Interoperability',
    question: 'What is the maturity of your enterprise integration platform (iPaaS, ESB, API Gateway)?',
    answerType: 'multiChoice',
    options: [
      { value: 0, label: 'None', description: 'Point-to-point integrations only' },
      { value: 25, label: 'Basic', description: 'Simple integration tools' },
      { value: 50, label: 'Platform exists', description: 'Enterprise integration platform in place' },
      { value: 75, label: 'Mature platform', description: 'Well-adopted platform with governance' },
      { value: 100, label: 'AI-enabled', description: 'Platform supports AI/ML workflows and real-time' },
    ],
    weight: 1.0,
    order: 1,
    isRequired: true,
  },
  {
    id: 'org-integration-002',
    code: 'INTEGRATION_002',
    category: 'technical',
    dimension: 'integration',
    dimensionName: 'Integration & Interoperability',
    question: 'How easily can new AI services be integrated with your existing systems?',
    answerType: 'scale',
    description: 'Consider time, effort, and technical barriers to integration.',
    helpText: 'Rate from 0 (very difficult) to 100 (seamless integration)',
    weight: 1.1,
    order: 2,
    isRequired: true,
  },
  {
    id: 'org-integration-003',
    code: 'INTEGRATION_003',
    category: 'technical',
    dimension: 'integration',
    dimensionName: 'Integration & Interoperability',
    question: 'What percentage of your data sources are accessible via self-service for analytics/AI?',
    answerType: 'percentage',
    weight: 0.9,
    order: 3,
    isRequired: true,
  },

  // Scalability & Performance (3 questions)
  {
    id: 'org-scale-001',
    code: 'SCALE_001',
    category: 'technical',
    dimension: 'scalability',
    dimensionName: 'Scalability & Performance',
    question: 'Does your infrastructure support auto-scaling for variable AI/ML workloads?',
    answerType: 'multiChoice',
    options: [
      { value: 0, label: 'No scaling', description: 'Fixed capacity infrastructure' },
      { value: 33, label: 'Manual scaling', description: 'Can scale but requires manual intervention' },
      { value: 66, label: 'Auto-scaling', description: 'Automated scaling for standard workloads' },
      { value: 100, label: 'Elastic AI', description: 'Fully elastic with GPU auto-scaling' },
    ],
    weight: 1.0,
    order: 1,
    isRequired: true,
  },
  {
    id: 'org-scale-002',
    code: 'SCALE_002',
    category: 'technical',
    dimension: 'scalability',
    dimensionName: 'Scalability & Performance',
    question: 'How mature are your performance monitoring and observability practices?',
    answerType: 'scale',
    description: 'Consider APM, logging, tracing, and AI model monitoring.',
    helpText: 'Rate from 0 (no monitoring) to 100 (comprehensive observability)',
    weight: 0.9,
    order: 2,
    isRequired: true,
  },
  {
    id: 'org-scale-003',
    code: 'SCALE_003',
    category: 'technical',
    dimension: 'scalability',
    dimensionName: 'Scalability & Performance',
    question: 'Can your systems handle real-time AI inference at production scale?',
    answerType: 'multiChoice',
    options: [
      { value: 0, label: 'No capability', description: 'No real-time AI in production' },
      { value: 33, label: 'Limited', description: 'Some real-time but with constraints' },
      { value: 66, label: 'Production ready', description: 'Real-time AI serving in production' },
      { value: 100, label: 'Optimized', description: 'High-performance, low-latency AI at scale' },
    ],
    weight: 1.0,
    order: 3,
    isRequired: true,
  },
]

// ============================================================
// CATEGORY 2: HUMAN (5 Dimensions)
// ============================================================

const humanQuestions: OrgMaturityQuestion[] = [
  // Leadership & Vision (3 questions)
  {
    id: 'org-leadership-001',
    code: 'LEADERSHIP_001',
    category: 'human',
    dimension: 'leadership_vision',
    dimensionName: 'Leadership & Vision',
    question: 'How committed is your CEO/executive team to AI transformation?',
    answerType: 'multiChoice',
    options: [
      { value: 0, label: 'Not committed', description: 'AI is not a leadership priority' },
      { value: 25, label: 'Interested', description: 'Some interest but no action' },
      { value: 50, label: 'Supportive', description: 'Supports AI initiatives but not driving' },
      { value: 75, label: 'Championing', description: 'Actively champions and funds AI' },
      { value: 100, label: 'AI-first mindset', description: 'AI is central to strategy and culture' },
    ],
    weight: 1.3,
    order: 1,
    isRequired: true,
  },
  {
    id: 'org-leadership-002',
    code: 'LEADERSHIP_002',
    category: 'human',
    dimension: 'leadership_vision',
    dimensionName: 'Leadership & Vision',
    question: 'Does your organization have a formal, documented AI strategy?',
    answerType: 'multiChoice',
    options: [
      { value: 0, label: 'No strategy', description: 'No AI strategy exists' },
      { value: 25, label: 'Informal ideas', description: 'Some ideas but nothing formal' },
      { value: 50, label: 'Basic strategy', description: 'Documented but not comprehensive' },
      { value: 75, label: 'Comprehensive strategy', description: 'Full strategy with roadmap and KPIs' },
      { value: 100, label: 'Living strategy', description: 'Continuously updated, integrated with business strategy' },
    ],
    weight: 1.2,
    order: 2,
    isRequired: true,
  },
  {
    id: 'org-leadership-003',
    code: 'LEADERSHIP_003',
    category: 'human',
    dimension: 'leadership_vision',
    dimensionName: 'Leadership & Vision',
    question: 'Do you have a dedicated AI/Digital leader (Chief AI Officer, CDO, etc.)?',
    answerType: 'multiChoice',
    options: [
      { value: 0, label: 'No role', description: 'No dedicated AI leadership' },
      { value: 33, label: 'Part-time', description: 'AI is part of another exec\'s responsibilities' },
      { value: 66, label: 'Dedicated leader', description: 'Full-time AI/Digital executive' },
      { value: 100, label: 'AI leadership team', description: 'C-level AI leader with dedicated team' },
    ],
    weight: 1.0,
    order: 3,
    isRequired: true,
  },

  // Culture & Change Readiness (3 questions)
  {
    id: 'org-culture-001',
    code: 'CULTURE_001',
    category: 'human',
    dimension: 'culture_change',
    dimensionName: 'Culture & Change Readiness',
    question: 'How would you describe your organization\'s innovation culture?',
    answerType: 'multiChoice',
    options: [
      { value: 0, label: 'Risk-averse', description: 'Innovation is discouraged or feared' },
      { value: 25, label: 'Cautious', description: 'Some innovation but heavily controlled' },
      { value: 50, label: 'Open', description: 'Innovation is accepted if proven' },
      { value: 75, label: 'Encouraging', description: 'Innovation is encouraged and resourced' },
      { value: 100, label: 'Innovation-driven', description: 'Experimentation is core to culture' },
    ],
    weight: 1.2,
    order: 1,
    isRequired: true,
  },
  {
    id: 'org-culture-002',
    code: 'CULTURE_002',
    category: 'human',
    dimension: 'culture_change',
    dimensionName: 'Culture & Change Readiness',
    question: 'How successful have recent major change initiatives been in your organization?',
    answerType: 'scale',
    description: 'Consider digital transformations, restructures, or system changes.',
    helpText: 'Rate from 0 (all failed) to 100 (highly successful)',
    weight: 1.1,
    order: 2,
    isRequired: true,
  },
  {
    id: 'org-culture-003',
    code: 'CULTURE_003',
    category: 'human',
    dimension: 'culture_change',
    dimensionName: 'Culture & Change Readiness',
    question: 'What level of employee resistance do you expect for AI adoption?',
    answerType: 'multiChoice',
    options: [
      { value: 100, label: 'Minimal resistance', description: 'Employees are eager for AI' },
      { value: 75, label: 'Low resistance', description: 'Generally positive with some concerns' },
      { value: 50, label: 'Moderate resistance', description: 'Mixed feelings, need for education' },
      { value: 25, label: 'High resistance', description: 'Significant concerns about AI' },
      { value: 0, label: 'Strong opposition', description: 'Active resistance to AI initiatives' },
    ],
    weight: 1.0,
    order: 3,
    isRequired: true,
  },

  // Skills & Talent (3 questions)
  {
    id: 'org-skills-001',
    code: 'SKILLS_001',
    category: 'human',
    dimension: 'skills_talent',
    dimensionName: 'Skills & Talent',
    question: 'What percentage of your workforce has AI/ML skills (from basic usage to expert)?',
    answerType: 'percentage',
    description: 'Include anyone who uses AI tools, not just data scientists.',
    weight: 1.1,
    order: 1,
    isRequired: true,
  },
  {
    id: 'org-skills-002',
    code: 'SKILLS_002',
    category: 'human',
    dimension: 'skills_talent',
    dimensionName: 'Skills & Talent',
    question: 'How would you rate your organization\'s AI training and upskilling programs?',
    answerType: 'multiChoice',
    options: [
      { value: 0, label: 'None', description: 'No AI training programs exist' },
      { value: 25, label: 'Ad-hoc', description: 'Occasional training, not systematic' },
      { value: 50, label: 'Basic programs', description: 'Regular training for some roles' },
      { value: 75, label: 'Comprehensive', description: 'Structured learning paths for all levels' },
      { value: 100, label: 'AI academy', description: 'Internal AI academy with certifications' },
    ],
    weight: 1.2,
    order: 2,
    isRequired: true,
  },
  {
    id: 'org-skills-003',
    code: 'SKILLS_003',
    category: 'human',
    dimension: 'skills_talent',
    dimensionName: 'Skills & Talent',
    question: 'How difficult is it for your organization to attract and retain AI talent?',
    answerType: 'multiChoice',
    options: [
      { value: 0, label: 'Very difficult', description: 'Cannot compete for AI talent' },
      { value: 25, label: 'Difficult', description: 'Struggle to fill AI roles' },
      { value: 50, label: 'Moderate', description: 'Some challenges but manageable' },
      { value: 75, label: 'Good', description: 'Competitive for most AI roles' },
      { value: 100, label: 'Excellent', description: 'Top destination for AI talent' },
    ],
    weight: 1.0,
    order: 3,
    isRequired: true,
  },

  // Collaboration & Communication (3 questions)
  {
    id: 'org-collab-001',
    code: 'COLLAB_001',
    category: 'human',
    dimension: 'collaboration',
    dimensionName: 'Collaboration & Communication',
    question: 'How effective is cross-functional collaboration on AI initiatives?',
    answerType: 'scale',
    description: 'Consider how well IT, business, and data teams work together.',
    helpText: 'Rate from 0 (siloed, no collaboration) to 100 (seamless collaboration)',
    weight: 1.1,
    order: 1,
    isRequired: true,
  },
  {
    id: 'org-collab-002',
    code: 'COLLAB_002',
    category: 'human',
    dimension: 'collaboration',
    dimensionName: 'Collaboration & Communication',
    question: 'Do you have communities of practice or knowledge-sharing forums for AI?',
    answerType: 'multiChoice',
    options: [
      { value: 0, label: 'None', description: 'No AI communities exist' },
      { value: 33, label: 'Informal', description: 'Informal chat groups or occasional meetups' },
      { value: 66, label: 'Formal communities', description: 'Structured CoPs with regular meetings' },
      { value: 100, label: 'Thriving ecosystem', description: 'Active communities driving innovation' },
    ],
    weight: 0.9,
    order: 2,
    isRequired: true,
  },
  {
    id: 'org-collab-003',
    code: 'COLLAB_003',
    category: 'human',
    dimension: 'collaboration',
    dimensionName: 'Collaboration & Communication',
    question: 'How widely are AI collaboration tools (Copilot, Notion AI, etc.) used in your org?',
    answerType: 'percentage',
    description: 'Percentage of knowledge workers using AI-powered collaboration tools.',
    weight: 1.0,
    order: 3,
    isRequired: true,
  },

  // Employee Experience (3 questions)
  {
    id: 'org-exp-001',
    code: 'EXP_001',
    category: 'human',
    dimension: 'employee_experience',
    dimensionName: 'Employee Experience',
    question: 'What is your organization\'s employee engagement score?',
    answerType: 'scale',
    description: 'Based on most recent engagement survey (eNPS or similar).',
    helpText: 'Rate from 0 (very low engagement) to 100 (highly engaged)',
    weight: 0.9,
    order: 1,
    isRequired: true,
  },
  {
    id: 'org-exp-002',
    code: 'EXP_002',
    category: 'human',
    dimension: 'employee_experience',
    dimensionName: 'Employee Experience',
    question: 'How mature is your digital employee experience (DEX) platform?',
    answerType: 'multiChoice',
    options: [
      { value: 0, label: 'Non-existent', description: 'No unified digital workplace' },
      { value: 25, label: 'Basic', description: 'Basic intranet and email' },
      { value: 50, label: 'Modern', description: 'Modern collaboration platform (Teams, Slack)' },
      { value: 75, label: 'Integrated', description: 'Integrated DEX with AI assistance' },
      { value: 100, label: 'AI-powered', description: 'AI-first employee experience platform' },
    ],
    weight: 1.0,
    order: 2,
    isRequired: true,
  },
  {
    id: 'org-exp-003',
    code: 'EXP_003',
    category: 'human',
    dimension: 'employee_experience',
    dimensionName: 'Employee Experience',
    question: 'Do employees feel their concerns about AI (job security, etc.) are heard?',
    answerType: 'scale',
    helpText: 'Rate from 0 (not heard at all) to 100 (concerns actively addressed)',
    weight: 1.1,
    order: 3,
    isRequired: true,
  },
]

// ============================================================
// CATEGORY 3: BUSINESS (7 Dimensions)
// ============================================================

const businessQuestions: OrgMaturityQuestion[] = [
  // Strategy & Alignment (3 questions)
  {
    id: 'org-strategy-001',
    code: 'STRATEGY_001',
    category: 'business',
    dimension: 'strategy_alignment',
    dimensionName: 'Strategy & Alignment',
    question: 'How well is your AI strategy aligned with overall business strategy?',
    answerType: 'scale',
    description: 'Consider whether AI initiatives directly support business goals.',
    helpText: 'Rate from 0 (no alignment) to 100 (fully integrated)',
    weight: 1.3,
    order: 1,
    isRequired: true,
  },
  {
    id: 'org-strategy-002',
    code: 'STRATEGY_002',
    category: 'business',
    dimension: 'strategy_alignment',
    dimensionName: 'Strategy & Alignment',
    question: 'Do you have clear KPIs and success metrics for AI initiatives?',
    answerType: 'multiChoice',
    options: [
      { value: 0, label: 'No metrics', description: 'AI success is not measured' },
      { value: 25, label: 'Basic metrics', description: 'Some usage/adoption metrics' },
      { value: 50, label: 'Business metrics', description: 'ROI and business impact tracked' },
      { value: 75, label: 'OKR framework', description: 'AI OKRs integrated with company goals' },
      { value: 100, label: 'Value realization', description: 'Comprehensive value tracking and attribution' },
    ],
    weight: 1.1,
    order: 2,
    isRequired: true,
  },
  {
    id: 'org-strategy-003',
    code: 'STRATEGY_003',
    category: 'business',
    dimension: 'strategy_alignment',
    dimensionName: 'Strategy & Alignment',
    question: 'How involved is the business side in defining AI use cases?',
    answerType: 'multiChoice',
    options: [
      { value: 0, label: 'IT-driven only', description: 'Business not involved in AI decisions' },
      { value: 25, label: 'Consulted', description: 'Business consulted but not driving' },
      { value: 50, label: 'Collaborative', description: 'Joint IT-business AI initiatives' },
      { value: 75, label: 'Business-led', description: 'Business leads with IT enabling' },
      { value: 100, label: 'Embedded', description: 'AI identification is everyone\'s job' },
    ],
    weight: 1.0,
    order: 3,
    isRequired: true,
  },

  // Process Optimization (3 questions)
  {
    id: 'org-process-001',
    code: 'PROCESS_001',
    category: 'business',
    dimension: 'process_optimization',
    dimensionName: 'Process Optimization',
    question: 'What percentage of your core business processes are documented and standardized?',
    answerType: 'percentage',
    description: 'Well-documented processes are easier to automate with AI.',
    weight: 1.0,
    order: 1,
    isRequired: true,
  },
  {
    id: 'org-process-002',
    code: 'PROCESS_002',
    category: 'business',
    dimension: 'process_optimization',
    dimensionName: 'Process Optimization',
    question: 'How mature is your process automation (RPA, workflow automation)?',
    answerType: 'multiChoice',
    options: [
      { value: 0, label: 'No automation', description: 'Fully manual processes' },
      { value: 25, label: 'Pilots', description: 'Testing automation in a few areas' },
      { value: 50, label: 'Scaling', description: 'Automation expanding across departments' },
      { value: 75, label: 'Enterprise', description: 'Automation is standard practice' },
      { value: 100, label: 'Intelligent automation', description: 'AI-powered intelligent automation' },
    ],
    weight: 1.1,
    order: 2,
    isRequired: true,
  },
  {
    id: 'org-process-003',
    code: 'PROCESS_003',
    category: 'business',
    dimension: 'process_optimization',
    dimensionName: 'Process Optimization',
    question: 'Do you have a Center of Excellence (CoE) for process improvement or automation?',
    answerType: 'boolean',
    weight: 0.9,
    order: 3,
    isRequired: true,
  },

  // Customer Centricity (3 questions)
  {
    id: 'org-customer-001',
    code: 'CUSTOMER_001',
    category: 'business',
    dimension: 'customer_centricity',
    dimensionName: 'Customer Centricity',
    question: 'How well do you leverage customer data for personalization and insights?',
    answerType: 'multiChoice',
    options: [
      { value: 0, label: 'Not at all', description: 'Customer data is siloed or unused' },
      { value: 25, label: 'Basic segmentation', description: 'Simple demographic segmentation' },
      { value: 50, label: 'Behavioral insights', description: 'Using behavior data for targeting' },
      { value: 75, label: 'Predictive', description: 'Predictive models for customer behavior' },
      { value: 100, label: 'AI-driven', description: 'Real-time AI personalization at scale' },
    ],
    weight: 1.1,
    order: 1,
    isRequired: true,
  },
  {
    id: 'org-customer-002',
    code: 'CUSTOMER_002',
    category: 'business',
    dimension: 'customer_centricity',
    dimensionName: 'Customer Centricity',
    question: 'Do you use AI in customer-facing interactions (chatbots, recommendations, etc.)?',
    answerType: 'multiChoice',
    options: [
      { value: 0, label: 'No AI', description: 'No AI in customer experience' },
      { value: 25, label: 'Basic chatbot', description: 'Simple FAQ chatbot' },
      { value: 50, label: 'AI-assisted', description: 'AI supports human agents' },
      { value: 75, label: 'AI-first', description: 'AI handles most interactions' },
      { value: 100, label: 'Autonomous CX', description: 'AI-driven end-to-end customer experience' },
    ],
    weight: 1.0,
    order: 2,
    isRequired: true,
  },
  {
    id: 'org-customer-003',
    code: 'CUSTOMER_003',
    category: 'business',
    dimension: 'customer_centricity',
    dimensionName: 'Customer Centricity',
    question: 'What is your Net Promoter Score (NPS) or customer satisfaction trend?',
    answerType: 'scale',
    helpText: 'Rate from 0 (declining/poor) to 100 (excellent/improving)',
    weight: 0.9,
    order: 3,
    isRequired: true,
  },

  // Innovation Capability (3 questions)
  {
    id: 'org-innovation-001',
    code: 'INNOVATION_001',
    category: 'business',
    dimension: 'innovation',
    dimensionName: 'Innovation Capability',
    question: 'Do you have a formal process for identifying and evaluating AI opportunities?',
    answerType: 'multiChoice',
    options: [
      { value: 0, label: 'No process', description: 'AI ideas are ad-hoc' },
      { value: 25, label: 'Informal', description: 'Informal idea collection' },
      { value: 50, label: 'Structured', description: 'Formal ideation and evaluation process' },
      { value: 75, label: 'Innovation pipeline', description: 'Continuous pipeline of AI opportunities' },
      { value: 100, label: 'AI innovation lab', description: 'Dedicated team for AI R&D' },
    ],
    weight: 1.1,
    order: 1,
    isRequired: true,
  },
  {
    id: 'org-innovation-002',
    code: 'INNOVATION_002',
    category: 'business',
    dimension: 'innovation',
    dimensionName: 'Innovation Capability',
    question: 'What percentage of R&D or technology budget is allocated to AI?',
    answerType: 'percentage',
    weight: 1.0,
    order: 2,
    isRequired: true,
  },
  {
    id: 'org-innovation-003',
    code: 'INNOVATION_003',
    category: 'business',
    dimension: 'innovation',
    dimensionName: 'Innovation Capability',
    question: 'How quickly can you take an AI idea from concept to production?',
    answerType: 'multiChoice',
    options: [
      { value: 0, label: 'Years', description: 'More than 12 months typically' },
      { value: 25, label: '6-12 months', description: 'Half a year to a year' },
      { value: 50, label: '3-6 months', description: 'A few months to half a year' },
      { value: 75, label: '1-3 months', description: 'Weeks to a few months' },
      { value: 100, label: 'Weeks', description: 'Rapid experimentation and deployment' },
    ],
    weight: 1.0,
    order: 3,
    isRequired: true,
  },

  // Financial Performance (3 questions)
  {
    id: 'org-financial-001',
    code: 'FINANCIAL_001',
    category: 'business',
    dimension: 'financial',
    dimensionName: 'Financial Performance',
    question: 'What is your organization\'s revenue growth trajectory?',
    answerType: 'multiChoice',
    options: [
      { value: 0, label: 'Declining', description: 'Revenue is decreasing' },
      { value: 25, label: 'Flat', description: 'Stable but no growth' },
      { value: 50, label: 'Modest growth', description: '1-10% annual growth' },
      { value: 75, label: 'Strong growth', description: '10-25% annual growth' },
      { value: 100, label: 'Hypergrowth', description: '25%+ annual growth' },
    ],
    weight: 0.8,
    order: 1,
    isRequired: true,
    forRoles: ['cfo', 'ceo'],
  },
  {
    id: 'org-financial-002',
    code: 'FINANCIAL_002',
    category: 'business',
    dimension: 'financial',
    dimensionName: 'Financial Performance',
    question: 'What is your annual AI investment budget (approximate)?',
    answerType: 'multiChoice',
    options: [
      { value: 0, label: 'No budget', description: 'No dedicated AI budget' },
      { value: 20, label: 'Under $100K', description: 'Small experiments only' },
      { value: 40, label: '$100K-$500K', description: 'Limited but real investment' },
      { value: 60, label: '$500K-$2M', description: 'Significant investment' },
      { value: 80, label: '$2M-$10M', description: 'Major strategic investment' },
      { value: 100, label: '$10M+', description: 'Transformational investment' },
    ],
    weight: 1.0,
    order: 2,
    isRequired: true,
    forRoles: ['cfo', 'ceo', 'cto'],
  },
  {
    id: 'org-financial-003',
    code: 'FINANCIAL_003',
    category: 'business',
    dimension: 'financial',
    dimensionName: 'Financial Performance',
    question: 'Have you achieved measurable ROI from AI investments?',
    answerType: 'multiChoice',
    options: [
      { value: 0, label: 'No AI investments', description: 'Haven\'t invested in AI yet' },
      { value: 25, label: 'No ROI yet', description: 'Invested but no measurable return' },
      { value: 50, label: 'Break-even', description: 'Roughly covering costs' },
      { value: 75, label: 'Positive ROI', description: 'Clear positive returns' },
      { value: 100, label: 'High ROI', description: 'Significant returns (3x+ investment)' },
    ],
    weight: 1.1,
    order: 3,
    isRequired: true,
  },

  // Partner Ecosystem (3 questions)
  {
    id: 'org-partner-001',
    code: 'PARTNER_001',
    category: 'business',
    dimension: 'partner_ecosystem',
    dimensionName: 'Partner Ecosystem',
    question: 'Do you have strategic partnerships with AI vendors or consultants?',
    answerType: 'multiChoice',
    options: [
      { value: 0, label: 'None', description: 'No AI partnerships' },
      { value: 25, label: 'Vendor relationships', description: 'Transactional vendor relationships' },
      { value: 50, label: 'Partners', description: 'A few strategic AI partners' },
      { value: 75, label: 'Ecosystem', description: 'Rich ecosystem of AI partners' },
      { value: 100, label: 'Co-innovation', description: 'Deep co-innovation partnerships' },
    ],
    weight: 0.9,
    order: 1,
    isRequired: true,
  },
  {
    id: 'org-partner-002',
    code: 'PARTNER_002',
    category: 'business',
    dimension: 'partner_ecosystem',
    dimensionName: 'Partner Ecosystem',
    question: 'How mature is your approach to evaluating and adopting AI solutions?',
    answerType: 'scale',
    description: 'Consider vendor evaluation, POC process, and procurement.',
    helpText: 'Rate from 0 (no process) to 100 (mature evaluation framework)',
    weight: 0.8,
    order: 2,
    isRequired: true,
  },
  {
    id: 'org-partner-003',
    code: 'PARTNER_003',
    category: 'business',
    dimension: 'partner_ecosystem',
    dimensionName: 'Partner Ecosystem',
    question: 'Do you participate in AI industry consortiums or standards bodies?',
    answerType: 'boolean',
    weight: 0.7,
    order: 3,
    isRequired: false,
  },

  // Risk Management (3 questions)
  {
    id: 'org-risk-001',
    code: 'RISK_001',
    category: 'business',
    dimension: 'risk_management',
    dimensionName: 'Risk Management',
    question: 'Do you have a formal AI risk assessment and management framework?',
    answerType: 'multiChoice',
    options: [
      { value: 0, label: 'None', description: 'No AI-specific risk framework' },
      { value: 25, label: 'Basic awareness', description: 'Aware of AI risks but no framework' },
      { value: 50, label: 'Risk identification', description: 'Risks identified and documented' },
      { value: 75, label: 'Risk management', description: 'Active risk management and mitigation' },
      { value: 100, label: 'Comprehensive', description: 'Full AI risk governance framework' },
    ],
    weight: 1.0,
    order: 1,
    isRequired: true,
  },
  {
    id: 'org-risk-002',
    code: 'RISK_002',
    category: 'business',
    dimension: 'risk_management',
    dimensionName: 'Risk Management',
    question: 'How well do you manage AI model risks (bias, drift, failure modes)?',
    answerType: 'scale',
    helpText: 'Rate from 0 (not managed) to 100 (comprehensive model risk management)',
    weight: 1.1,
    order: 2,
    isRequired: true,
  },
  {
    id: 'org-risk-003',
    code: 'RISK_003',
    category: 'business',
    dimension: 'risk_management',
    dimensionName: 'Risk Management',
    question: 'Do you have contingency plans for AI system failures?',
    answerType: 'boolean',
    description: 'Fallback procedures when AI systems are unavailable.',
    weight: 0.9,
    order: 3,
    isRequired: true,
  },
]

// ============================================================
// CATEGORY 4: AI ADOPTION (6 Dimensions)
// ============================================================

const aiAdoptionQuestions: OrgMaturityQuestion[] = [
  // AI Use Cases (3 questions)
  {
    id: 'org-aiuse-001',
    code: 'AIUSE_001',
    category: 'ai_adoption',
    dimension: 'ai_use_cases',
    dimensionName: 'AI Use Cases',
    question: 'How many AI use cases do you have in production?',
    answerType: 'multiChoice',
    options: [
      { value: 0, label: 'None', description: 'No AI in production' },
      { value: 20, label: '1-2', description: 'A couple of pilots or small deployments' },
      { value: 40, label: '3-5', description: 'Several production use cases' },
      { value: 60, label: '6-10', description: 'Multiple established AI applications' },
      { value: 80, label: '11-20', description: 'AI broadly deployed' },
      { value: 100, label: '20+', description: 'AI pervasive across organization' },
    ],
    weight: 1.2,
    order: 1,
    isRequired: true,
  },
  {
    id: 'org-aiuse-002',
    code: 'AIUSE_002',
    category: 'ai_adoption',
    dimension: 'ai_use_cases',
    dimensionName: 'AI Use Cases',
    question: 'What is the business impact of your AI use cases?',
    answerType: 'multiChoice',
    options: [
      { value: 0, label: 'No impact', description: 'No measurable business impact' },
      { value: 25, label: 'Efficiency gains', description: 'Some productivity improvements' },
      { value: 50, label: 'Cost reduction', description: 'Measurable cost savings' },
      { value: 75, label: 'Revenue impact', description: 'AI contributing to revenue' },
      { value: 100, label: 'Strategic advantage', description: 'AI is a key differentiator' },
    ],
    weight: 1.3,
    order: 2,
    isRequired: true,
  },
  {
    id: 'org-aiuse-003',
    code: 'AIUSE_003',
    category: 'ai_adoption',
    dimension: 'ai_use_cases',
    dimensionName: 'AI Use Cases',
    question: 'What types of AI are you using?',
    answerType: 'multiChoice',
    options: [
      { value: 0, label: 'None', description: 'Not using AI' },
      { value: 20, label: 'Simple ML', description: 'Basic analytics and predictions' },
      { value: 40, label: 'Applied ML', description: 'Various ML models in production' },
      { value: 60, label: 'Advanced AI', description: 'Deep learning, NLP, computer vision' },
      { value: 80, label: 'Generative AI', description: 'Using LLMs and generative models' },
      { value: 100, label: 'AI-first', description: 'Full spectrum including AI agents' },
    ],
    weight: 1.0,
    order: 3,
    isRequired: true,
  },

  // ML Operations (3 questions)
  {
    id: 'org-mlops-001',
    code: 'MLOPS_001',
    category: 'ai_adoption',
    dimension: 'ml_operations',
    dimensionName: 'ML Operations',
    question: 'Do you have an MLOps platform for managing the ML lifecycle?',
    answerType: 'multiChoice',
    options: [
      { value: 0, label: 'None', description: 'No MLOps infrastructure' },
      { value: 25, label: 'Basic tools', description: 'Jupyter notebooks and manual deployment' },
      { value: 50, label: 'Partial MLOps', description: 'Some automation for model training/deployment' },
      { value: 75, label: 'Full MLOps', description: 'Comprehensive platform (Kubeflow, MLflow, etc.)' },
      { value: 100, label: 'Enterprise MLOps', description: 'End-to-end automation with governance' },
    ],
    weight: 1.1,
    order: 1,
    isRequired: true,
  },
  {
    id: 'org-mlops-002',
    code: 'MLOPS_002',
    category: 'ai_adoption',
    dimension: 'ml_operations',
    dimensionName: 'ML Operations',
    question: 'How well do you manage model versioning, lineage, and reproducibility?',
    answerType: 'scale',
    helpText: 'Rate from 0 (not managed) to 100 (fully governed)',
    weight: 1.0,
    order: 2,
    isRequired: true,
  },
  {
    id: 'org-mlops-003',
    code: 'MLOPS_003',
    category: 'ai_adoption',
    dimension: 'ml_operations',
    dimensionName: 'ML Operations',
    question: 'Do you have automated monitoring for model performance and drift?',
    answerType: 'multiChoice',
    options: [
      { value: 0, label: 'None', description: 'No model monitoring' },
      { value: 33, label: 'Manual checks', description: 'Periodic manual review' },
      { value: 66, label: 'Basic monitoring', description: 'Some automated alerts' },
      { value: 100, label: 'Comprehensive', description: 'Full observability with auto-retraining' },
    ],
    weight: 0.9,
    order: 3,
    isRequired: true,
  },

  // AI Governance (3 questions)
  {
    id: 'org-aigov-001',
    code: 'AIGOV_001',
    category: 'ai_adoption',
    dimension: 'ai_governance',
    dimensionName: 'AI Governance',
    question: 'Do you have an AI ethics board or governance committee?',
    answerType: 'multiChoice',
    options: [
      { value: 0, label: 'None', description: 'No AI governance structure' },
      { value: 33, label: 'Informal', description: 'Ad-hoc ethics discussions' },
      { value: 66, label: 'Committee', description: 'Formal AI governance committee' },
      { value: 100, label: 'Board + policies', description: 'Ethics board with formal policies and review process' },
    ],
    weight: 1.1,
    order: 1,
    isRequired: true,
  },
  {
    id: 'org-aigov-002',
    code: 'AIGOV_002',
    category: 'ai_adoption',
    dimension: 'ai_governance',
    dimensionName: 'AI Governance',
    question: 'How do you address bias and fairness in AI systems?',
    answerType: 'multiChoice',
    options: [
      { value: 0, label: 'Not addressed', description: 'No bias mitigation efforts' },
      { value: 25, label: 'Awareness', description: 'Aware but no formal process' },
      { value: 50, label: 'Testing', description: 'Test for bias before deployment' },
      { value: 75, label: 'Active mitigation', description: 'Systematic bias detection and correction' },
      { value: 100, label: 'Continuous fairness', description: 'Ongoing monitoring and improvement' },
    ],
    weight: 1.0,
    order: 2,
    isRequired: true,
  },
  {
    id: 'org-aigov-003',
    code: 'AIGOV_003',
    category: 'ai_adoption',
    dimension: 'ai_governance',
    dimensionName: 'AI Governance',
    question: 'Do you have documented AI policies covering use, development, and deployment?',
    answerType: 'boolean',
    weight: 0.9,
    order: 3,
    isRequired: true,
  },

  // Data Science Maturity (3 questions)
  {
    id: 'org-ds-001',
    code: 'DS_001',
    category: 'ai_adoption',
    dimension: 'data_science',
    dimensionName: 'Data Science Maturity',
    question: 'How large is your data science / ML engineering team?',
    answerType: 'multiChoice',
    options: [
      { value: 0, label: 'None', description: 'No dedicated data science team' },
      { value: 20, label: '1-2 people', description: 'Small team or individual' },
      { value: 40, label: '3-5 people', description: 'Small dedicated team' },
      { value: 60, label: '6-15 people', description: 'Established team' },
      { value: 80, label: '16-50 people', description: 'Large team with specializations' },
      { value: 100, label: '50+', description: 'Enterprise-scale AI organization' },
    ],
    weight: 1.0,
    order: 1,
    isRequired: true,
  },
  {
    id: 'org-ds-002',
    code: 'DS_002',
    category: 'ai_adoption',
    dimension: 'data_science',
    dimensionName: 'Data Science Maturity',
    question: 'What is the maturity of your analytics capabilities?',
    answerType: 'multiChoice',
    options: [
      { value: 0, label: 'None', description: 'No analytics capabilities' },
      { value: 25, label: 'Descriptive', description: 'Basic reporting and dashboards' },
      { value: 50, label: 'Diagnostic', description: 'Root cause analysis' },
      { value: 75, label: 'Predictive', description: 'Forecasting and predictions' },
      { value: 100, label: 'Prescriptive', description: 'AI-driven recommendations and actions' },
    ],
    weight: 1.1,
    order: 2,
    isRequired: true,
  },
  {
    id: 'org-ds-003',
    code: 'DS_003',
    category: 'ai_adoption',
    dimension: 'data_science',
    dimensionName: 'Data Science Maturity',
    question: 'How well do data scientists and engineers collaborate with business teams?',
    answerType: 'scale',
    helpText: 'Rate from 0 (siloed) to 100 (embedded in business)',
    weight: 0.9,
    order: 3,
    isRequired: true,
  },

  // Automation Level (3 questions)
  {
    id: 'org-auto-001',
    code: 'AUTO_001',
    category: 'ai_adoption',
    dimension: 'automation',
    dimensionName: 'Automation Level',
    question: 'What is your RPA (Robotic Process Automation) adoption level?',
    answerType: 'multiChoice',
    options: [
      { value: 0, label: 'None', description: 'No RPA implementation' },
      { value: 25, label: 'Piloting', description: 'Testing RPA in limited areas' },
      { value: 50, label: 'Scaling', description: 'RPA expanding across departments' },
      { value: 75, label: 'Established', description: 'RPA is standard practice' },
      { value: 100, label: 'Intelligent automation', description: 'AI-enhanced RPA (hyperautomation)' },
    ],
    weight: 1.0,
    order: 1,
    isRequired: true,
  },
  {
    id: 'org-auto-002',
    code: 'AUTO_002',
    category: 'ai_adoption',
    dimension: 'automation',
    dimensionName: 'Automation Level',
    question: 'What percentage of repetitive tasks in your organization are automated?',
    answerType: 'percentage',
    weight: 1.1,
    order: 2,
    isRequired: true,
  },
  {
    id: 'org-auto-003',
    code: 'AUTO_003',
    category: 'ai_adoption',
    dimension: 'automation',
    dimensionName: 'Automation Level',
    question: 'Do you use AI for decision support or decision automation?',
    answerType: 'multiChoice',
    options: [
      { value: 0, label: 'None', description: 'No AI-assisted decisions' },
      { value: 25, label: 'Basic support', description: 'AI provides information for decisions' },
      { value: 50, label: 'Recommendations', description: 'AI recommends actions' },
      { value: 75, label: 'Human-in-loop', description: 'AI decides with human approval' },
      { value: 100, label: 'Autonomous', description: 'Some decisions fully automated' },
    ],
    weight: 1.0,
    order: 3,
    isRequired: true,
  },

  // AI Infrastructure (3 questions)
  {
    id: 'org-aiinfra-001',
    code: 'AIINFRA_001',
    category: 'ai_adoption',
    dimension: 'ai_infrastructure',
    dimensionName: 'AI Infrastructure',
    question: 'What compute infrastructure do you have for AI/ML?',
    answerType: 'multiChoice',
    options: [
      { value: 0, label: 'None', description: 'No dedicated AI compute' },
      { value: 25, label: 'Laptops/desktops', description: 'Standard machines only' },
      { value: 50, label: 'Cloud compute', description: 'Cloud-based CPU/GPU instances' },
      { value: 75, label: 'Managed AI services', description: 'AWS SageMaker, Azure ML, etc.' },
      { value: 100, label: 'AI platform', description: 'Enterprise AI platform with specialized hardware' },
    ],
    weight: 1.0,
    order: 1,
    isRequired: true,
  },
  {
    id: 'org-aiinfra-002',
    code: 'AIINFRA_002',
    category: 'ai_adoption',
    dimension: 'ai_infrastructure',
    dimensionName: 'AI Infrastructure',
    question: 'Do you have access to GPU or specialized AI hardware?',
    answerType: 'multiChoice',
    options: [
      { value: 0, label: 'No GPUs', description: 'CPU only' },
      { value: 33, label: 'On-demand GPUs', description: 'Cloud GPUs when needed' },
      { value: 66, label: 'Dedicated GPUs', description: 'Reserved GPU capacity' },
      { value: 100, label: 'Enterprise GPU', description: 'Large-scale GPU/TPU infrastructure' },
    ],
    weight: 0.9,
    order: 2,
    isRequired: true,
  },
  {
    id: 'org-aiinfra-003',
    code: 'AIINFRA_003',
    category: 'ai_adoption',
    dimension: 'ai_infrastructure',
    dimensionName: 'AI Infrastructure',
    question: 'Are you using LLM APIs or self-hosted large language models?',
    answerType: 'multiChoice',
    options: [
      { value: 0, label: 'Not using LLMs', description: 'No LLM usage' },
      { value: 33, label: 'API only', description: 'Using OpenAI, Anthropic, etc. APIs' },
      { value: 66, label: 'Hybrid', description: 'APIs plus some self-hosted' },
      { value: 100, label: 'Enterprise LLM', description: 'Self-hosted or fine-tuned LLMs' },
    ],
    weight: 1.0,
    order: 3,
    isRequired: true,
  },
]

// ============================================================
// EXPORT ALL QUESTIONS
// ============================================================

export const orgMaturityQuestions: OrgMaturityQuestion[] = [
  ...technicalQuestions,
  ...humanQuestions,
  ...businessQuestions,
  ...aiAdoptionQuestions,
]

export const orgMaturityCategories = {
  technical: {
    id: 'technical',
    name: 'Technical Foundation',
    description: 'Infrastructure, data, security, and integration capabilities',
    icon: 'Server',
    color: '#3B82F6', // blue
    weight: 1.0,
    dimensions: ['tech_infrastructure', 'data_quality', 'security_compliance', 'integration', 'scalability'],
  },
  human: {
    id: 'human',
    name: 'Human Capital',
    description: 'Leadership, culture, skills, and employee experience',
    icon: 'Users',
    color: '#10B981', // emerald
    weight: 1.0,
    dimensions: ['leadership_vision', 'culture_change', 'skills_talent', 'collaboration', 'employee_experience'],
  },
  business: {
    id: 'business',
    name: 'Business Strategy',
    description: 'Strategy alignment, processes, customers, and financial performance',
    icon: 'TrendingUp',
    color: '#8B5CF6', // violet
    weight: 1.0,
    dimensions: ['strategy_alignment', 'process_optimization', 'customer_centricity', 'innovation', 'financial', 'partner_ecosystem', 'risk_management'],
  },
  ai_adoption: {
    id: 'ai_adoption',
    name: 'AI Adoption',
    description: 'Use cases, operations, governance, and AI infrastructure',
    icon: 'Brain',
    color: '#F59E0B', // amber
    weight: 1.0,
    dimensions: ['ai_use_cases', 'ml_operations', 'ai_governance', 'data_science', 'automation', 'ai_infrastructure'],
  },
}

export const orgMaturityDimensions = {
  // Technical
  tech_infrastructure: { name: 'Technology Infrastructure', category: 'technical' },
  data_quality: { name: 'Data Quality & Governance', category: 'technical' },
  security_compliance: { name: 'Security & Compliance', category: 'technical' },
  integration: { name: 'Integration & Interoperability', category: 'technical' },
  scalability: { name: 'Scalability & Performance', category: 'technical' },
  // Human
  leadership_vision: { name: 'Leadership & Vision', category: 'human' },
  culture_change: { name: 'Culture & Change Readiness', category: 'human' },
  skills_talent: { name: 'Skills & Talent', category: 'human' },
  collaboration: { name: 'Collaboration & Communication', category: 'human' },
  employee_experience: { name: 'Employee Experience', category: 'human' },
  // Business
  strategy_alignment: { name: 'Strategy & Alignment', category: 'business' },
  process_optimization: { name: 'Process Optimization', category: 'business' },
  customer_centricity: { name: 'Customer Centricity', category: 'business' },
  innovation: { name: 'Innovation Capability', category: 'business' },
  financial: { name: 'Financial Performance', category: 'business' },
  partner_ecosystem: { name: 'Partner Ecosystem', category: 'business' },
  risk_management: { name: 'Risk Management', category: 'business' },
  // AI Adoption
  ai_use_cases: { name: 'AI Use Cases', category: 'ai_adoption' },
  ml_operations: { name: 'ML Operations', category: 'ai_adoption' },
  ai_governance: { name: 'AI Governance', category: 'ai_adoption' },
  data_science: { name: 'Data Science Maturity', category: 'ai_adoption' },
  automation: { name: 'Automation Level', category: 'ai_adoption' },
  ai_infrastructure: { name: 'AI Infrastructure', category: 'ai_adoption' },
}

export const orgMaturityAssessmentConfig = {
  id: 'org-maturity',
  name: 'Organizational AI Maturity Assessment',
  description: 'Comprehensive enterprise AI readiness assessment across 23 dimensions',
  shortDescription: 'Enterprise AI maturity assessment',
  estimatedMinutes: 40,
  totalQuestions: orgMaturityQuestions.length,
  categories: Object.values(orgMaturityCategories),
  dimensionCount: Object.keys(orgMaturityDimensions).length,
  version: '1.0.0',
  isActive: true,
}

export default orgMaturityQuestions
